# .travis.yml
language: node_js
node_js:
  - "18"

dist: focal

cache:
  yarn: true
  directories:
    - node_modules

install:
  # use frozen lockfile to ensure deterministic installs
  - yarn install --frozen-lockfile

script:
  # build your production bundle (Vite default outputs to `dist`)
  - yarn build

# optional: run tests (uncomment if you have tests to run on CI)
# before_deploy:
#  - yarn test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN   # set this in Travis repo settings (secure)
  local_dir: dist               # Vite default build dir
  on:
    branch: todo-test                # change to your default branch if needed
