version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          command: yarn install
          name: Install dependencies
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
      

 