version: 2.1
workflows:
  version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/node:22.18.0
    steps:
      - checkout
      - run:
          command: yarn install
          name: Install dependencies
      - run:
          command: yarn build
          name: Build application
      - run:
          command: yarn test
          name: Run tests
      

